name: Nodejs yarn workflow netlify
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
            node-version: '12.x'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get yarn cache dir
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Setup cache
        uses: actions/cache@v1
        with:
            path: ${{ steps.yarn-cache-dir.outputs.dir }}
            key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            restore-keys: |
              ${{ runner.os }}-modules-${{ runner.os }}-
      - name: Install node -modules
        run: yarn Install --frozen-lockfile
      - name: Linting
        run: yarn lint
      - name: Testing
        run: CI=true yarn test
  
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        with:
            args: deploy --dir=build --prod
  
 